language: node_js
node_js:
  - '14'

notifications:
  slack: thefortesting:LDvOuBBnMJGVBe4muJ4tXpxZ

cache:
  directories:
    - node_modules

install:
  - yarn install --frozen-lockfile

script:
  - yarn run build
  - yarn run test
