version: 2.1
orbs:
  node: circleci/node@4.7
  slack: circleci/slack@4.10.1
jobs:
  notify:
    docker:
      - image: "cimg/base:stable"
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
workflows:
  test:
    jobs:
      - node/test:
          version: "16.10"
          pkg-manager: yarn
  send-notification:
    jobs:
      - notify:
          context: slack-secrets
