version: 2.1

orbs:
  node: circleci/node@4.7
  slack: circleci/slack@4.10.1

workflows:
  deploy_and_notify:
    jobs:
      - deploy:
          context: slack-templates
          context: github

jobs:
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - node/install-packages
      - run: npm run test
      - run: npm run build
      - run: git config --global user.email "$GITHUB_EMAIL"
      - run: git config --global user.name "$GITHUB_NAME"
      - run: npm run deploy
      - slack/notify:
          event: pass
          template: success_tagged_deploy
