version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  deploy:
    docker:
      - image: circleci/node
    steps:
      - add_ssh_keys:
          fingerprints:
            - "1a:ec:4b:cc:e1:b2:76:42:f9:8d:a7:1b:1c:b3:b3:d8"
      - checkout
      - run:
          name: "Deploy"
          command: |
            git config --global user.email "$GITHUB_EMAIL"
            git config --global user.name "$GITHUB_NAME"
            npm install
            npm run build
            npm run deploy
      # Notify
      - run:
        when: pass
        command: |
          echo {\"username\": \"CircleCI\",\"attachments\": [{ \"color\": \"#36a64f\", \"text\": \"Success\"}]} > /tmp/payload.json
          curl -X POST "$Slack_API" -H "Content-Type: application/json" -d @/tmp/payload.json
      - run:
        when: fail
        command: |
          echo {\"username\": \"CircleCI\",\"attachments\": [{ \"color\": \"#ff0000\", \"text\": \"Fail\"}]} > /tmp/payload.json
          curl -X POST "$Slack_API" -H "Content-Type: application/json" -d @/tmp/payload.json

workflows:
  Deploy_to_Github_Page:
    jobs:
      - deploy:
          context:
            - Slack
            - Github
