version: 2.1
orbs:
  node: circleci/node@4.7
  slack: circleci/slack@4.10.1
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: npm run test
      - slack/notify:
          event: pass
          template: success_tagged_test
workflows:
  test_and_notify:
    jobs:
      - test:
          context: slack-templates
