version: 2.1

orbs:
  node: circleci/node@4.7
  slack: circleci/slack@4.10.1

jobs:
  deploy:
    docker:
      - image: circleci/node
    steps:
      - add_ssh_keys:
          fingerprints:
            - "1a:ec:4b:cc:e1:b2:76:42:f9:8d:a7:1b:1c:b3:b3:d8"
      - checkout
      - node/install-packages
      - run:
          command: |
            git config --global user.email "$GITHUB_EMAIL"
            git config --global user.name "$GITHUB_NAME"
            npm run test
            npm run build
            npm run deploy
      - slack/notify:
          event: fail
          template: fail_tagged_deploy
      - slack/notify:
          event: pass
          template: success_tagged_deploy

workflows:
  deploy_and_notify:
    jobs:
      - deploy:
          context:
            - slack-templates
            - github
