version: 2.1

orbs:
  node: circleci/node@4.7
  slack: circleci/slack@4.10.1

jobs:
  deploy:
    docker:
      - image: circleci/node
    steps:
      - add_ssh_keys:
          fingerprints:
            - "1a:ec:4b:cc:e1:b2:76:42:f9:8d:a7:1b:1c:b3:b3:d8"
      - checkout
      - node/install-packages
      # - run: npm run test
      - run: npm run build
      - run:
          name: "Deploy"
          command: |
            git config --global user.email "$GITHUB_EMAIL"
            git config --global user.name "$GITHUB_NAME"
            npm run deploy

workflows:
  Deploy_to_Github_Page:
    jobs:
      - deploy:
          context:
            - slack-templates
            - github
