version: 2.1
orbs:
  node: circleci/node@4.7
  slack: circleci/slack@4.10.1
jobs:
  notify:
    docker:
      - image: "cimg/base:stable"
    steps:
      - slack/notify:
          event: pass
          template: success_tagged_test
workflows:
  test_and_notify:
    jobs:
      - node/test:
          version: "16.10"
          pkg-manager: yarn
      - notify:
          context: slack-templates
