name: sample_website CI/CD
run-name: sample_website build
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: build
          retention-days: 1
  deployment:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://nsja.github.io/sample_website/
    runs-on: self-hosted
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
