name: sample_website CI
run-name: sample_website build
on: [push]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]
    steps:
      - name: Check Souce Code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
